name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.4.0

    - name: Read go version
      id: read_versions
      run: |
        echo "::set-output name=go::$(go mod edit -json | jq -r .Go)"

    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: "${{ steps.read_versions.outputs.go }}"
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: go build
      run: go build -v .

    - name: go test
      run: go test ./...

